from django.urls import path
from . import views
app_name = "dashboard"
urlpatterns = [
    path(
        "",
        views.home,
        name="home",
    ),
    path(
        "properties/<slug:slug>/",
        views.property_manage,
        name="property_manage",
    ),
    path(
        "properties/<slug:slug>/sections/add/",
        views.section_add,
        name="section_add",
    ),
    path(
        "properties/<slug:slug>/sections/<int:section_id>/edit/",
        views.section_edit,
        name="section_edit",
    ),
    path(
        "properties/<slug:slug>/sections/<int:section_id>/delete/",
        views.section_delete,
        name="section_delete",
    ),
    path(
        "properties/<slug:slug>/sections/<int:section_id>/move-up/",
        views.section_move_up,
        name="section_move_up",
    ),
    path(
        "properties/<slug:slug>/sections/<int:section_id>/move-down/",
        views.section_move_down,
        name="section_move_down",
    ),
    path(
        "properties/<slug:slug>/sections/reorder/",
        views.section_reorder,
        name="section_reorder",
    ),
    path(
        "properties/<slug:slug>/qr-locations/add/",
        views.qr_location_add,
        name="qr_location_add",
    ),
    path(
        "properties/<slug:slug>/qr-locations/<int:location_id>/",
        views.qr_location_detail,
        name="qr_location_detail",
        ),
    path(
        "properties/<slug:slug>/qr-locations/<int:location_id>/edit/",
        views.qr_location_edit,
        name="qr_location_edit",
        ),
    path(
        "properties/<slug:slug>/qr-locations/<int:location_id>/delete/",
        views.qr_location_delete,
        name="qr_location_delete",
    ),
    path(
        "properties/<slug:slug>/sections/<int:section_id>/links/add/",
        views.section_link_add,
        name="section_link_add",
    ),
    path(
        "properties/<slug:slug>/sections/<int:section_id>/links/<int:link_id>/delete/",
        views.section_link_delete,
        name="section_link_delete",
    ),
    path(
        "properties/<slug:slug>/sections/<int:section_id>/items/add/",
        views.section_item_add,
        name="section_item_add",
    ),
    path(
        "properties/<slug:slug>/sections/<int:section_id>/items/<int:item_id>/delete/",
        views.section_item_delete,
        name="section_item_delete",
    ),
    path(
        "properties/<slug:slug>/sections/<int:section_id>/items/<int:item_id>/edit/",
        views.section_item_edit,
        name="section_item_edit",
    ),
]