from django.urls import path
from . import views
app_name = "properties"
urlpatterns = [
    path(
        "p/<slug:slug>/",
        views.guest_portal,
        name="guest_portal",
    ),
    path(
        "p/<slug:slug>/qr/",
        views.property_qr,
        name="property_qr",
    ),
    path(
        "p/<slug:slug>/qr/download/",
        views.download_property_qr,
        name="download_property_qr",
    ),
    path(
        "p/<slug:slug>/qr/card/",
        views.qr_card,
        name="qr_card",
    ),
    path(
        "p/<slug:slug>/sections/<int:section_id>/view/",
        views.track_section_view,
        name="track_section_view",
    ),
    path(
        "p/<slug:slug>/q/<slug:location_slug>/",
        views.qr_location_redirect,
        name="qr_location_redirect",
    ),
    path(
        "p/<slug:slug>/q/<slug:location_slug>/qr/",
        views.qr_location_image,
        name="qr_location_image",
    ),
    path(
        "p/<slug:slug>/q/<slug:location_slug>/qr/download/",
        views.download_qr_location_image,
        name="download_qr_location_image",
    ),
    path(
        "p/<slug:slug>/q/<slug:location_slug>/card/",
        views.qr_location_card,
        name="qr_location_card",
    ),
]