# Generated by Django 6.1 on 2026-08-19 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_sections', to='properties.property')),
            ],
            options={
                'ordering': ('sort_order', 'title'),
                'constraints': [models.UniqueConstraint(fields=('property', 'slug'), name='unique_guest_section_slug_per_property')],
            },
        ),
    ]
