# Generated by Django 6.1 on 2026-08-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_guestsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='property_logos/'),
        ),
    ]
