# Generated by Django 6.1 on 2026-08-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestsection',
            name='icon',
            field=models.CharField(choices=[('info', 'Information'), ('wifi', 'Wi-Fi'), ('breakfast', 'Breakfast / Dining'), ('parking', 'Parking'), ('checkout', 'Check-in / Check-out'), ('facilities', 'Facilities'), ('local', 'Local Area'), ('faq', 'FAQ'), ('contact', 'Contact')], default='info', max_length=50),
        ),
    ]
