# Generated by Django 6.1 on 2026-08-20 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertymembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPortalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_visits', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='GuestSectionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_views', to='properties.property')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='properties.guestsection')),
            ],
        ),
    ]
