# Generated by Django 6.1 on 2026-08-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_guestportalvisit_guestsectionview'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestportalvisit',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='guestsectionview',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
