# Generated by Django 6.1 on 2026-08-20 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_guestportalvisit_session_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_locations', to='properties.property')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='properties.qrlocation')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='properties.property')),
            ],
        ),
        migrations.AddConstraint(
            model_name='qrlocation',
            constraint=models.UniqueConstraint(fields=('property', 'slug'), name='unique_qr_location_slug_per_property'),
        ),
    ]
