# Generated by Django 6.1 on 2026-08-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_qrlocation_qrscan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestsection',
            name='action_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guestsection',
            name='action_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='guestsection',
            name='copy_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guestsection',
            name='copy_value',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
