# Generated by Django 6.1 on 2026-08-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_guestsectionlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestsection',
            name='wifi_network',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='guestsection',
            name='wifi_password',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
