# Generated by Django 6.1 on 2026-08-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_guestsection_wifi_network_guestsection_wifi_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestsection',
            name='check_in_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='guestsection',
            name='check_out_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='guestsection',
            name='check_times_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
