# Generated by Django 6.1 on 2026-08-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_guestsection_check_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestsection',
            name='breakfast_location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='guestsection',
            name='breakfast_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='guestsection',
            name='breakfast_weekday_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guestsection',
            name='breakfast_weekend_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
