# Generated by Django 6.1 on 2026-08-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_guestsection_breakfast_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestsection',
            name='section_type',
            field=models.CharField(choices=[('generic', 'General information'), ('wifi', 'Wi-Fi'), ('stay_times', 'Check-in / Check-out'), ('breakfast', 'Breakfast / Dining')], default='generic', max_length=30),
        ),
    ]
