# Generated by Django 6.1 on 2026-08-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_guestsection_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestsection',
            name='parking_availability',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='guestsection',
            name='parking_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='guestsection',
            name='parking_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='guestsection',
            name='parking_registration',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='guestsection',
            name='section_type',
            field=models.CharField(choices=[('generic', 'General information'), ('wifi', 'Wi-Fi'), ('stay_times', 'Check-in / Check-out'), ('breakfast', 'Breakfast / Dining'), ('parking', 'Parking')], default='generic', max_length=30),
        ),
    ]
