# Generated by Django 6.1 on 2026-08-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_guestsectionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestsectionitem',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guestsectionitem',
            name='distance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guestsectionitem',
            name='link_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guestsectionitem',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='guestsection',
            name='section_type',
            field=models.CharField(choices=[('generic', 'General information'), ('wifi', 'Wi-Fi'), ('stay_times', 'Check-in / Check-out'), ('breakfast', 'Breakfast / Dining'), ('parking', 'Parking'), ('facilities', 'Facilities')], default='generic', max_length=30),
        ),
    ]
